### ISSUE TITLE
Get  a  bug

### ISSUE THREAD

**Issue by lovechang1986** [meridionaljet/pygrads#1]
while i use function ga.exp('lat') then message show,how can i resolve it?

 'invalid exchange metadata (idim,jdim)=(%d,%d) - make sure <%s> is valid and that lon/lat is varying.'%(id,jd,expr)
grads.gacore.GrADSError: 'invalid exchange metadata (idim,jdim)=(0,77724220109037511232075876794368) - make sure <lat> is valid and that lon/lat is varying.'

**Comment by lovechang1986** [comment]
my python enviroment:
anaconda 2.1, 
python 2.7.9,
numpy and scipy is lastest version.

**Comment by meridionaljet** [comment]
This repo was an early attempt to convert PyGrADS to Python 3, and remains buggy. It is now depreciated, and you should check out Py3GrADS instead: https://github.com/meridionaljet/py3grads

I apologize for the inconvenience. This repo will be removed soon in deference to the one linked above.
